authors:
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png
  ronald_luo:
    name: Ronald Luo
    description: I'm A Student
    avatar: avatar.jpg
